### ISSUE TITLE
java.lang.NoClassDefFoundError: javax/xml/bind/JAXBException

### ISSUE THREAD

**Issue by xiaohan2012** [keelm/SeCo-MLC#1]
Hi,

When I run:

`java -jar SeCo-MLC.jar -baselearner config/precision.xml -arff data/genbase-train.arff -xml data/genbase.xml -arff-test data
/genbase-test.arff -remainingInstancesPercentage 0.1 -readAllCovered true -skipThresholdPercentage 0.01 -predictZeroRules true -useMultilabelHeads true -averagingStrategy micro-averaging -evaluationStrategy rule-dependent`

It gives me:

```
<ThresholdPercentage 0.01 -predictZeroRules true -useMultilabelHeads true -averagingStrategy micro-averaging -evaluationStrategy rule-dependent
Arguments:

-baselearner config/precision.xml
-arff data/genbase-train.arff
-xml data/genbase.xml
-test-arff null
-remainingInstancesPercentage 0.1
-readAllCovered true
-skipThresholdPercentage 0.01
-predictZeroRules true
-useMultilabelHeads true
-evaluationStrategy rule-dependent
-averagingStrategy micro-averaging


Exception in thread "main" java.lang.NoClassDefFoundError: javax/xml/bind/JAXBException
        at mulan.data.MultiLabelInstances.loadLabelsMeta(MultiLabelInstances.java:513)
        at mulan.data.MultiLabelInstances.<init>(MultiLabelInstances.java:166)
        at de.tu_darmstadt.ke.seco.Main.main(Main.java:118)
Caused by: java.lang.ClassNotFoundException: javax.xml.bind.JAXBException
        at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:581)
        at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:178)
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:522)
        ... 3 more
```

My environment:

- OS: MacOS Monterey
- Java version:

```
openjdk 11.0.14.1 2022-02-08
OpenJDK Runtime Environment Temurin-11.0.14.1+1 (build 11.0.14.1+1)
OpenJDK 64-Bit Server VM Temurin-11.0.14.1+1 (build 11.0.14.1+1, mixed mode)
```

Can you help?

**Comment by keelm** [comment]
Did you manage to solve that?
